CREATE TABLE price_data (
    id VARCHAR,
    prices_amountMax FLOAT,
    prices_amountMin FLOAT,
    prices_availability BOOLEAN,
    prices_condition CHAR,
    prices_currency CHAR,
    prices_dateSeen DATE,
    prices_isSale BOOLEAN,
    prices_merchant VARCHAR,
    prices_shipping FLOAT,
    prices_sourceURLs VARCHAR,
    asins VARCHAR,
    brand VARCHAR,
    categories VARCHAR,
    dateAdded DATE,
    dateUpdated DATE,
    ean INT,
    imageURLs VARCHAR,
    keys VARCHAR,
    manufacturer VARCHAR,
    manufacturerNumber VARCHAR,
    name VARCHAR,
    primaryCategories VARCHAR,
    sourceURLs VARCHAR,
    upc INT,
    weight FLOAT,
    PRIMARY KEY (id)
);