CREATE TABLE price_data (
	index INT,
	id VARCHAR,
    prices_amountMax FLOAT,
    prices_amountMin FLOAT,
    prices_availability BOOLEAN,
    prices_condition VARCHAR,
    prices_currency VARCHAR,
    prices_dateSeen DATE,
    prices_isSale BOOLEAN,
    prices_merchant VARCHAR,
    prices_shipping VARCHAR,
    prices_sourceURLs VARCHAR,
    asins VARCHAR,
    brand VARCHAR,
    categories VARCHAR,
    dateAdded DATE,
    dateUpdated DATE,
    ean VARCHAR,
    imageURLs VARCHAR,
    keys VARCHAR,
    manufacturer VARCHAR,
    manufacturerNumber VARCHAR,
    name VARCHAR,
    primaryCategories VARCHAR,
    sourceURLs VARCHAR,
    upc VARCHAR,
    weight VARCHAR,
    PRIMARY KEY (index)
);